version: '3.8'

services:
  sermon-app:
    image: ghcr.io/orakysec/sermon-app:latest
    networks:
      - YkaroNET
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sermon-app.rule=Host(`sermon.ykaromarques.com`)"
      - "traefik.http.routers.sermon-app.entrypoints=websecure"
      - "traefik.http.routers.sermon-app.tls=true"
      - "traefik.http.routers.sermon-app.tls.certresolver=letsencrypt"
      - "traefik.http.services.sermon-app.loadbalancer.server.port=3000"

networks:
  YkaroNET:
    external: true
